### ISSUE TITLE
3.3.1. Implementirati favorite

### ISSUE THREAD

**Issue by enovak1** [AIR-FOI-HR/AIR1920#12]
Najdraže znamenitosti

**Comment by efusic** [comment]
Implementiran pregled spremljenih znamenitosti. Pregled je vidljiv na FavoriteFragmentu.

Korisnik znamenitost sprema tako da klikne na gumb u obliku srca na željenoj znamenitosti. Ako je znamenitost spremljena tad je gumb crvene boje, u suprotnom je sive. Osim samog pregleda spremljenih znamenitosti, korisnik znamenitosti istim postupkom može maknuti iz favorita te ih može pretraživati po nazivu ili dijelu naziva.

**Comment by efusic** [comment]
1. Prikaz spremljenih i nespremljenih znamenitosti na pocetnom screenu (HomeFragment) 

<img src= "https://images.zenhubusercontent.com/5df9276ba703605a99235ef5/13e95b89-941c-47c2-a480-288ad8268e30"  width="200">


2. Prikaz spremljenih znamenitosti na screenu Favoriti (FavoriteFragment)

<img src= "https://images.zenhubusercontent.com/5df9276ba703605a99235ef5/128cb43f-da94-4615-af0f-459b305f22ff"  width="200">


3. Prikaz pretrazivanja spremljene znamenitosti na Favoritima

<img src= "https://images.zenhubusercontent.com/5df9276ba703605a99235ef5/3fdcb43e-94fc-4b34-a49c-f5653090d35b"  width="200">
