### ISSUE TITLE
4.1. Ocjenjivanje, komentiranje

### ISSUE THREAD

**Issue by enovak1** [AIR-FOI-HR/AIR1920#13]
### **Opis:** 
- Svaku znamenitost moguće je recenzirati, a u slučaju da se ne napiše opis onda se ostavlja samo ocjena.
- Svaku recenziju ostali korisnici mogu ocijeniti koliko je relevantna.

### **Zadaće**:
- [x] Mogućnost unosa ocjene znamenitosti.
- [x] Mogućnost recenziranje (unosa komentara) (isto ko ocjena ali sa tekstom).
- [x] Ocjenjivanje tuđih komentara sa "upvote"-om i "downvote"-om.

**Comment by adretar** [comment]
## Ocjena recenzija i njihov unos

Svaki korisnik može jednom na određenu znamenitost napisati recenziju. Unos ocjene je obavezan, a opisa recenzije nije. Ocjena mora biti od 1 do 5.  Funkcija bodoviZaRecenziju() daje korisnicima bodove što su napisali recenziju. Na prikau recenzije može se vidjeti opis recenije, ocjena te slika, ime i prezime korisnika koji je recenzirao.
![Izrezak4.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/5561743e-63a6-48df-b660-df0631b89602)

## Like i Dislike
Korisnici mogu svaku recenziju ocjeniti sa sviđa mi se i ne sviđa mi se .  Ako korisnik dobije sviđa mi se ispod ikone prsta prema gore povećava mu se broj likeova. Ako korisnik makne like ili ga promjeni u dislike zbroj likeova se smanjuje za 1. Ako korisnik označi dislike broj dislikeova se povećava, a ako se dislike makne ili promijeni u like zbroj dislikeova se smanjuje.


![Izrezak.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/ca913963-8398-4652-8d12-74d88e2296cb)

![Izrezak2.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/eed47c46-6f65-4eba-b9ba-21af91543939)
