### ISSUE TITLE
3.1.3. / 4.1.1. Implementirati pregled recenzija

### ISSUE THREAD

**Issue by enovak1** [AIR-FOI-HR/AIR1920#14]
Pregled recenzija drugih korisnika za znamenitost.

**Comment by adretar** [comment]
#Pregled recenzija
Na svakoj znamenitosti možemo vidjeti recenzije svih korisnika koji su recenzirali za tu znamenutost. Ako korisnik označi neku recenziju sa sviđa mi se tada ikona palca prema gore pozeleni. Ako označi sa ne sviđa mi se tada ikona palac prema dolje pozeleni. Također možemo vidjeti prosječnu ocjenu za znaznamenitost u obliku RateBara. Recenzirati se može na detaljnoj stranici znamenitosti.
![84562940_864680360654581_3733129142107897856_n.jpg](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/92e1cd4e-3efe-407c-b78a-07ebc4ba270e)

# Dohvaćanje recenzija
Recenzije se dohvaćaju uz pomoć idZnamenitosti kako bi prave recenzije bile prikazane na pravoj znamenitosti. U toj funkciji kada dohvaćamo recenzije i njihove ocjene ujedno računamo prosječnu ocjenu za tu znamenitost.
![Izrezak.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/10c3c471-a828-4f68-8ab3-f097bdfc3fcb)
![Izrezak2.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/30f94865-1007-46d6-a557-ebbb82a346a5)

# Like/dislike mijenjanje boja
Pritiskom na like i dislike dolazi do mijenjanja boja i računa se brojač za likeove i dislikeove.
![Izrezak3.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/da2c20d2-027b-4ae6-8e34-6e49656439b7)
