### ISSUE TITLE
4.2. Gamification

### ISSUE THREAD

**Issue by enovak1** [AIR-FOI-HR/AIR1920#16]
### **Opis:** 
- Ocjenjivanjem i komentiranjem korisnik dobiva bodove, a bodove gubi ako mu ostali korisnici recenziju označe s „ne sviđa mi se“. 
- Korisnici s većim levelom bi trebali dati dojam pouzdanosti recenzije. Leveliranje je smišljeno za motivaciju korištenja aplikacije.

### **Zadaće**:
- [x] Postaviti da se izračuna koji je level korisnik na temelju njegove aktivnosti (u BP tablica _komentar_ i _ocjena_komentara_).
- [x] Prikazati korisnikov level pored njegovog imena (i na profilu i na njegovim komentarima pored imena)
- [x] Dodjeljivanje titula na profilu kada korisnik dostegne novi level.

**Comment by adretar** [comment]
#Gamification
Svaki korisik korištenjem aplikacije može dobiti ili gubiti bodove. Prikaz bodova korisnika vidi se na korisničkom profilu.

##Dobivanje bodova pisanjem recenzija
Svaki korisnik može pisati jednu recenziju na određenu znamenitost. Ako je korisnik recenzirao znamenitost dobiva 150 bodova.
![Izrezak.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/93e2681b-606a-465a-bd7a-08a13a072fe0)
Funkcija bodoviZaRecenziju() poziva se u dodavanju recenzija u bazu podataka.

##Dobivanje bodova za likeanje/dislikanje tuđih recenzija
Ako je korisnik likeao ili dislikeao određenu recenziju dobiva 50 bodova. Da bi se to ostvarilo poziva se funkcija prikazana na slici ispod.
![Izrezak2.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/b56488df-55de-4470-97c4-bc3fbdcc75eb)

##Micanje označenog likea ili dislikea
Ako korisnik označi like/dislikea pa nakon toga ga odznači on gubi 50 bodova jer nije ocjenio recenziju.
![Izrezak3.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/fc86d0e2-74d5-43d3-aa59-4acac946266e)
Ako označi like pa nakon toga promijeni u dislike samo će jednom dobiti 50 bodova ne dva ili više puta.
Ove funkcije se pozivaju pritiskom gumba like ili dislike.
