### ISSUE TITLE
Implementacija baze

### ISSUE THREAD

**Issue by enovak1** [AIR-FOI-HR/AIR1920#17]
Izrada baze u samoj aplikaciji

**Comment by lucosic** [comment]
1. ERA dijagram, ali tipove podataka gledajte na popisu tablica i atributa!!
![CultureAround.PNG](https://images.zenhubusercontent.com/5db88d98a7e95f00017a08ce/edbea8e0-1529-4abf-9330-74b8b117f5b0)

2. Popis tablica, opis tablica, atributi, tipovi atributa, detalji vezano za atribute i popis vanjskih ključeva
[https://app.zenhub.com/files/217946643/9613051a-4cbb-481a-87e2-adfef165dfec/download](https://app.zenhub.com/files/217946643/9613051a-4cbb-481a-87e2-adfef165dfec/download)

**Comment by enovak1** [comment]
Slozena je lokalna baza prema SQL skripti sa DataGrip-a i stavljeno je na github na zasebni branch "LocalDB" tako da se moze poceti kodirati aplikacija.
DAO trenutno ima samo ispis iz tablice "Korisnik" i to za sve korisnike ili za odredenog korisnika prema primarnom kljucu (Korisnicko ime) a sama baza je trenutno prazna.

**Comment by lucosic** [comment]
Ova baza podataka je zamijenjena **Firebase-om**!

# [Postavljenje Firebase-a za projekt](https://app.zenhub.com/workspaces/air1920-5db64bc20f039400010003b5/issues/air-foi-hr/air1920/31)
