### ISSUE TITLE
2.3. Prijedlozi destinacija

### ISSUE THREAD

**Issue by lucosic** [AIR-FOI-HR/AIR1920#23]
### **Opis:** 
- Znamenitosti su predložene prema **korisnikovoj lokaciji** i **ocjeni** koju ima. 
- Postoji mogućnost filtriranja prema kategoriji.

### **Zadaće**:

- [x] Filtriranje destinacija po prosječnoj ocjeni svih korisnika u recenzijama

**Comment by lucosic** [comment]
[2.1.1. Izrada početne stranice aplikacije](https://app.zenhub.com/workspaces/air1920-5db64bc20f039400010003b5/issues/air-foi-hr/air1920/32) je dosla slična izradi ove podfunkcionalnosti. Glavna razlika je u sortiranju sadržaja.

**Comment by adretar** [comment]
# Prijedlozi destinacija

Prijedlozi destinacije prikazuju nam destinacije na način da se one sortiraju po prosječnoj ocjeni korisnika. Tu prosječnu ocjenu dobivamo tako da korisnici recenziraju, odnosno daju ocjenu određenoj destinaciji.

## 1. Izgled prijedloga destinacija
Kada otvorimo prijedloge destinacija možemo vidjeti recyclerView koji nam pokazuje sortiranu listu znamenitosti po prosječnoj ocjeni korisnika. 

<img src="https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/bdead6f2-7d19-47c9-b4fa-7e2f7bb57625" width="200">

## 2. Dohvaćanje znamenitosti
Za početak mora se postaviti recyclerView te dohvatiti sve znamenitosti koje postoje u bazi
<img src="https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/12302556-8f4e-40b7-abea-01dfb186f193" width="500">
Ove linije koda pišemo u klasi RecommendedFragment.

## 3. Sortiranje znamenitosti
Da bismo mogli Znamenitosti sortirati po nekom njihovom određenom svojstvu (u ovome slučaju prosječnu ocjenu) mora se implementirati Comparable interface te postaviti compare.to() metodu. To se implementira u klasi Znamenitosti.

![Izrezak3.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/2f41bdb7-7533-4ae0-955e-c31fe3469f0a)
Vidi se implementacija Comparable interfacea.

![Izrezak4.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/2905cc18-255c-4155-9e36-f56f8e12fff0)
compare to() metoda.

Kada se to definiralo vraćamo se na RecommendedFragment.

Tada s Collections.sort() možemo sortirati listu, odnosno dohvaćamo znamenitosti, sortiramo ih pa ih prikažemo

![Izrezak2.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/9a015937-91d3-4e54-8e2c-060f93cd50f7)
