### ISSUE TITLE
Prilagodba prototipa

### ISSUE THREAD

**Issue by lucosic** [AIR-FOI-HR/AIR1920#25]
- [x] Izrada posebnog prikaza stranice znamenitosti za 3 kategorije od:
    - Kazalište
    - Muzej
    - Park
    - Galerija
    - Spomenik
    - Kino
    - ...

**Comment by adretar** [comment]
Prototip se trebao prilagoditi neregistriranom korisniku tako da se na prijavu dodao gumb preskoči koji neregistriranog korisnika prebacuje na naslovnu stranicu gdje on može tražiti znamenitosti, filtrirati ih po gradu ili određenoj kategoriji i vidjeti detaljan prikaz određene znamenitosti. U slučaju da želi pristupiti nekim drugim elementima (lokacija, profil, favoriti) u navigacijskoj traci, dobiva upozorenje da se mora prijaviti ili registrirati. Na slikama možemo vidjeti promjene na stranici prijava i prozor upozorenja da se korisnik mora prijaviti ili registrirati.

![prijavaPreskoci.PNG] (https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/f9d470be-b0b3-4cad-8b7d-80c5c1e31431)

![upozorenje.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/3d5686ad-19ea-467f-911e-8469a1d52a40)

**Comment by adretar** [comment]
Nakon toga trebali su se bolje prilagoditi primjeri koje predstavljamo u aplikaciji tako da se stave pravilne kategorije i znamenitosti koje ću se predstavljati u aplikaciji.
![naslivnicaIspravaniPrimjeri.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/22579c6c-45ec-4080-9c38-01c856147897)

**Comment by adretar** [comment]
I posljednje što se trebalo prilagoditi je detaljan prikaz znamenitosti. Na svakom detaljnom prikazu znamenitosti postoje jednaki osnovi elementi kao što su naslov, slika znamenitosti, adresa znamenitosti i karte. Ali neki elementi su prilagođeni određenom detaljnom prikazu, kao na primjer u detaljnom prikazu kina vidimo cjenik karata, na spomenicima se nalazi kratki opis tog spomenika, na detaljnom pregledu galerija možemo vidjeti slike koje su se predstavljale u toj galeriji i slično. Također spomenike i šetališta ne možemo recenzirati.

![1.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/5b60ed12-77db-48eb-b23e-008e26306eb2)
Slika 1. Detaljan prikaz kazališta

![2.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/3bf578c9-ab48-4742-9086-f55f783ae857)
Slika 2. Detaljan prikaz kina

![3.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/6ae3145a-155b-424c-a3cd-f03b38dc7acb)
Slika 3. Detaljan prikaz galerija

![4.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/78038488-88a3-4a51-960c-b23010c96873)
Slika 4. Detaljan prikaz muzeja

![6.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/a2f3e599-505f-40f7-b818-b79c608969f7)
Slika 5. Detaljan prikaz šetališta

![7.PNG](https://images.zenhubusercontent.com/5dfa9c51b123dfe2ba12e6a8/e3305865-0ec6-4e5f-adf0-225dc8a69578)
Slika 6. Detaljan prikaz spomenika
