### ISSUE TITLE
2.1.1. Izrada početne stranice aplikacije

### ISSUE THREAD

**Issue by enovak1** [AIR-FOI-HR/AIR1920#32]

**Comment by lucosic** [comment]
Nad početnom stranicom tj. home fragmentom napravljeno je sljedeće:
- prikaz znamenitosti preuzetih s firebase-a
- filtriranje prema kategorijama
- filtriranje prema lokacijama

Iako se ne čini u dizajnerskom smislu najpraktičnije bilo mi je važno ostvariti povlačenje zapisa iz baze i filtriranje prema kategoriji i lokaciji.

U buduće treba još napraviti **filtriranje prema nazivu** i **učiniti praktičnijim** (izgled).

**Comment by lucosic** [comment]
Sve znamenitosti su prikazane u recyclerview-u (id: "home_recycler") tako što se koriste:
- Filteri:
  - gumbi za uključivanje ili isključivanje prikaza kategorija
  - SearchView = tekstualna trazilica
  - odabrane lokacije na AlertDialog-u
- lista svih znamenitosti "znamenitosti" i lista prikazanih znamenitosti "prikazaneZnamenitosti"
  - ako nisu uključeni filteri onda je lista svih znamenitosti jednaka listi prikazanih znamenitosti
  - nakon postavljanja jednog od filtera (osim SearchView-a), funkcijom "`promijeniPrikazPodataka()`" se prikazuju
    - znamenitosti prema filterima lokacija : `private List<Znamenitost> filtrirajZnamenitostiPremaLokaciji(List<Znamenitost> prikazaneZnamenitosti){...}`
    - filterima kategorija : `private List<Znamenitost> filtrirajZnamenitostiPremaKategoriji(List<Znamenitost> prikazaneZnamenitosti{...}`
  - na kraju funkcije "`promijeniPrikazPodataka()`" zamijenjuje se postojeća lista znamenitosti (koja se nalazi u recycle adapteru sa novom listom znamenitosti "prikazaneZnamenitosti"
    - `znamenitostRecyclerAdapter.setZnamenitosti(prikazaneZnamenitosti);`
    - `znamenitostRecyclerAdapter.notifyDataSetChanged();`
- lista lokacija i lista odabranih lokacija
- Kada se mijenja tekst unutar **tekstualne tražilice** poziva se metoda koja filtrira znamenitosti prema stringu naziva znamenitosti. Onda se zamijenjuje se postojeća lista znamenitosti (koja se nalazi u recycle adapteru sa novom listom znamenitosti "prikazaneZnamenitosti". Kada se zatvori tražilica poziva se prethodno navedena funkcija "promijeniPrikazPodataka()".
```
private void pretraziTrazilicom(){
        List<Znamenitost> prikazaneZnamenitosti = new ArrayList<Znamenitost>();
        for (Znamenitost znamenitost: znamenitosti){
            if (znamenitost.getNaziv().toLowerCase().contains(trazilica.getQuery().toString().toLowerCase()))
                prikazaneZnamenitosti.add(znamenitost);
        }
        znamenitostRecyclerAdapter.setZnamenitosti(prikazaneZnamenitosti);
        znamenitostRecyclerAdapter.notifyDataSetChanged();
}
```
- ZnamenitostViewHolder
  - prikazuje CardView definiran u "znamenitost_list_item.xml"
  - instancira se unutar ZnamenitostRecyclerAdapter.java
  - popunjava dijelove CardView-a na temelju jedne znamenitosti koju dobiva preko javne funkcije "bindToData"

```
public void bindToData(Znamenitost znamenitost, Context context){
        this.selectedZnamenitost = znamenitost;
        znamenitostName.setText(znamenitost.getNaziv());
        znamenitostDesc.setText(znamenitost.getOpis());
        String urlSlike = znamenitost.getLokacijaSlike();
        Picasso.with(itemView
                .getContext())
                .load(urlSlike)
                .into(znamenitostImage);
    }
```

- ZnamenitostRecyclerAdapter
  - Služi za povezivanje podataka (ovdje lista znamenitosti) sa karticama unutar recyclerView-a
  - Dobiva listu znamenitosti i poziva ZnamenitostViewHolder metodu `bindToData`
```
public class ZnamenitostRecyclerAdapter extends RecyclerView.Adapter<ZnamenitostViewHolder> {
    private Context context;
    private List<Znamenitost> znamenitosti;

    public void setZnamenitosti(List<Znamenitost> znamenitosti) {
        this.znamenitosti = znamenitosti;
    }
    public ZnamenitostRecyclerAdapter(Context context, @NonNull List<Znamenitost> znamenitosti) {
        this.context = context;
        this.znamenitosti = znamenitosti;
    }
    @NonNull
    @Override
    public ZnamenitostViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View znamenitostView = LayoutInflater.from(parent.getContext()).inflate(R.layout.znamenitost_list_item, parent, false);
        return new ZnamenitostViewHolder(znamenitostView);
    }
    @Override
    public void onBindViewHolder(@NonNull ZnamenitostViewHolder holder, int position) {
        holder.bindToData(znamenitosti.get(position), context);
    }
    @Override
    public int getItemCount() {
        return znamenitosti.size();
    }
}
```
- RecyclerView
  - poseban view koji sadrži CardView-ove (naši ZnamenitostViewHolder.java i znamenitost_list_item.xml)
  - da bi prikazivao podatke potrebna je lista znamenitosti i instanciran znemenitostRecycleAdapter
  - postavlja se na principu:
```
@BindView(R.id.home_recycler)
RecyclerView recyclerView;

...

        List<Znamenitost> znamenitosti;
        znamenitosti = new ArrayList<>(); //ovdje su znamenitosti prazne, ali inače stavljamo punu listu
        //instanciranje adaptera sa postavljenim znamenitostima
        ZnamenitostRecyclerAdapter znamenitostRecyclerAdapter = new ZnamenitostRecyclerAdapter(getActivity(), znamenitosti);
        //recyclerView se poveže s adapterom i postavlja se njegov LayoutManager
        recyclerView.setAdapter(znamenitostRecyclerAdapter);
        recyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));
```
  - za svaku promjenu prikaza znamenitosti moramo ubaciti novu listu znamenitosti u adapter i osvježiti holdere
```
znamenitostRecyclerAdapter.setZnamenitosti(prikazaneZnamenitosti);
znamenitostRecyclerAdapter.notifyDataSetChanged();
```

**Comment by lucosic** [comment]
## **Filtriranje kategorijama i lokacijama**
<img src="https://images.zenhubusercontent.com/5db88d98a7e95f00017a08ce/72d18761-ce4f-4393-b995-ea7b7ff89fa9" width="300"/>

## **Filtriranje tekstualnom tražilicom**
<img src="https://images.zenhubusercontent.com/5db88d98a7e95f00017a08ce/bee7f935-b22b-42ff-bb35-790f9bd234e2" width="300"/>
