### ISSUE TITLE
2.1. Pretraživanje preko tražilice

### ISSUE THREAD

**Issue by enovak1** [AIR-FOI-HR/AIR1920#5]
### **Opis:** 
- Mogućnost pretrage baze podataka znamenitosti prema nazivu, adresi, gradu i kategoriji.

### **Zadaće**:
- [x] Izvesti upit nad bazom i prikazati podatke

**Comment by lucosic** [comment]
Pretraživanje je moguće samo scrollanjem svih znamenitosti i filtriranjem prema kategoriji.

Filtriranje prema nazivu adresi i gradu nisam napravio.

**Comment by lucosic** [comment]
Update 3. sprint na linku:
### [2.1.1. Izrada početne stranice aplikacije](https://app.zenhub.com/workspaces/air1920-5db64bc20f039400010003b5/issues/air-foi-hr/air1920/32)
